import math

def format_timestamp(ms):
    ms = int(ms)  # Ensure ms is an integer
    seconds, milliseconds = divmod(ms, 1000)
    minutes, seconds = divmod(seconds, 60)
    hours, minutes = divmod(minutes, 60)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d},{milliseconds:03d}"

def split_text(text, max_words=15):
    words = text.split()
    lines = []
    for i in range(0, len(words), max_words):
        lines.append(" ".join(words[i:i+max_words]))
    return lines

def to_srt(transcript):
    srt_content = ""
    count = 1
    
    # Check if transcript.text exists and is not empty
    if not hasattr(transcript, 'text') or not transcript.text:
        return "No transcription available."
    
    # Use the full transcript as one segment if utterances are not available
    lines = split_text(transcript.text)
    
    # If words are available, use them to create time-aligned segments
    if hasattr(transcript, 'words') and transcript.words:
        # Group words into reasonable segments
        segments = []
        current_segment = {"text": "", "start": None, "end": None}
        
        for i, word in enumerate(transcript.words):
            if current_segment["start"] is None:
                current_segment["start"] = word.start
            
            current_segment["text"] += " " + word.text if current_segment["text"] else word.text
            current_segment["end"] = word.end
            
            # Create a new segment after approximately 10-15 words or at punctuation
            if (i + 1) % 15 == 0 or (word.text and word.text[-1] in ['.', '!', '?']):
                segments.append(current_segment)
                current_segment = {"text": "", "start": None, "end": None}
        
        # Add the last segment if it has content
        if current_segment["text"]:
            segments.append(current_segment)
        
        # Generate SRT content from segments
        for segment in segments:
            start_time = format_timestamp(segment["start"])
            end_time = format_timestamp(segment["end"])
            
            srt_content += f"{count}\n{start_time} --> {end_time}\n{segment['text']}\n\n"
            count += 1
    else:
        # Fallback if no words with timestamps are available
        # Estimate timestamps based on total audio duration
        total_duration = transcript.audio_duration if hasattr(transcript, 'audio_duration') else 0
        if total_duration <= 0:
            total_duration = 60000  # Default to 1 minute if duration unknown
        
        duration_per_line = total_duration / len(lines) if lines else 0
        
        for i, line in enumerate(lines):
            start_time_ms = i * duration_per_line
            end_time_ms = start_time_ms + duration_per_line

            start_time = format_timestamp(start_time_ms)
            end_time = format_timestamp(end_time_ms)
            
            srt_content += f"{count}\n{start_time} --> {end_time}\n{line}\n\n"
            count += 1
            
    return srt_content

def to_ts(transcript):
    # MPEG-TS does not have a standard text-based subtitle format like SRT.
    # It usually embeds subtitles as bitmap images (DVB subtitles) or teletext.
    # For simplicity, we will generate a simple text format that can be used with some players.
    # This is not a standard-compliant .ts subtitle format.
    ts_content = ""
    
    # Check if transcript.text exists and is not empty
    if not hasattr(transcript, 'text') or not transcript.text:
        return "No transcription available."
    
    # If words are available, use them to create time-aligned segments
    if hasattr(transcript, 'words') and transcript.words:
        for word in transcript.words:
            start_time_sec = word.start / 1000
            ts_content += f"[{start_time_sec:.2f}] {word.text}\n"
    else:
        # Fallback if no words with timestamps are available
        start_time_sec = 0
        ts_content += f"[{start_time_sec:.2f}] {transcript.text}\n"
            
    return ts_content

def to_ass(transcript):
    ass_content = "[Script Info]\nTitle: Generated by Video Transcription App\nScriptType: v4.00+\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
    
    # Check if transcript.text exists and is not empty
    if not hasattr(transcript, 'text') or not transcript.text:
        return ass_content + "Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,No transcription available."
    
    # If words are available, use them to create time-aligned segments
    if hasattr(transcript, 'words') and transcript.words:
        # Group words into reasonable segments
        segments = []
        current_segment = {"text": "", "start": None, "end": None}
        
        for i, word in enumerate(transcript.words):
            if current_segment["start"] is None:
                current_segment["start"] = word.start
            
            current_segment["text"] += " " + word.text if current_segment["text"] else word.text
            current_segment["end"] = word.end
            
            # Create a new segment after approximately 10-15 words or at punctuation
            if (i + 1) % 15 == 0 or (word.text and word.text[-1] in ['.', '!', '?']):
                segments.append(current_segment)
                current_segment = {"text": "", "start": None, "end": None}
        
        # Add the last segment if it has content
        if current_segment["text"]:
            segments.append(current_segment)
        
        # Generate ASS content from segments
        for segment in segments:
            start_time = format_ass_timestamp(segment["start"])
            end_time = format_ass_timestamp(segment["end"])
            
            ass_content += f"Dialogue: 0,{start_time},{end_time},Default,,0,0,0,,{segment['text']}\n"
    else:
        # Fallback if no words with timestamps are available
        lines = split_text(transcript.text)
        total_duration = transcript.audio_duration if hasattr(transcript, 'audio_duration') else 0
        if total_duration <= 0:
            total_duration = 60000  # Default to 1 minute if duration unknown
            
        duration_per_line = total_duration / len(lines) if lines else 0

        for i, line in enumerate(lines):
            start_time_ms = i * duration_per_line
            end_time_ms = start_time_ms + duration_per_line

            start_time = format_ass_timestamp(start_time_ms)
            end_time = format_ass_timestamp(end_time_ms)

            ass_content += f"Dialogue: 0,{start_time},{end_time},Default,,0,0,0,,{line}\n"
            
    return ass_content

def format_ass_timestamp(ms):
    ms = int(ms)  # Ensure ms is an integer
    seconds, milliseconds = divmod(ms, 1000)
    minutes, seconds = divmod(seconds, 60)
    hours, minutes = divmod(minutes, 60)
    centiseconds = math.floor(milliseconds / 10)
    return f"{hours:01d}:{minutes:02d}:{seconds:02d}.{centiseconds:02d}" 